version: "3.3"
services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - redis
    links:
      - mongo

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #     - "35729:35729"
  #   volumes:
  #     - ./client:/app
  #   depends_on:
  #     - server

  redis:
    image: redis

  mongo:
    image: mongo:latest
    restart: always
    # env_file: .env
    ports:
      - "27017:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
